"""empty message

Revision ID: 4a3f6b86e713
Revises: 4cff13133248
Create Date: 2022-06-17 10:31:04.206714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3f6b86e713'
down_revision = '4cff13133248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gene', 'gene',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('gene', 'id')
    op.drop_column('gene', 'timepoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('timepoint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gene', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('gene', 'gene',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
