"""empty message

Revision ID: 4cff13133248
Revises: 4c4f4afdd994
Create Date: 2022-06-03 15:28:02.945614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cff13133248'
down_revision = '4c4f4afdd994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timepoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gene')
    # ### end Alembic commands ###
