"""empty message

Revision ID: 6ed892be7364
Revises: 8ea93f0e275e
Create Date: 2022-06-17 14:10:07.303502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed892be7364'
down_revision = '8ea93f0e275e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_gene_filter', 'gene_filtered', ['gene', 'timepoint'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_gene_filter', table_name='gene_filtered')
    # ### end Alembic commands ###
