"""empty message

Revision ID: 74fd89d42ced
Revises: 
Create Date: 2022-06-03 10:37:25.662530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fd89d42ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.Unicode(length=255), nullable=True),
    sa.Column('korean', sa.Unicode(length=255), nullable=True),
    sa.Column('romanian', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
