"""empty message

Revision ID: 8ea93f0e275e
Revises: 4a3f6b86e713
Create Date: 2022-06-17 11:47:41.043154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ea93f0e275e'
down_revision = '4a3f6b86e713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_filtered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timepoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene_unfiltered',
    sa.Column('gene', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('gene')
    )
    op.drop_table('gene')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
    sa.Column('gene', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_table('gene_unfiltered')
    op.drop_table('gene_filtered')
    # ### end Alembic commands ###
